### ISSUE TITLE
Causing server to freeze

### ISSUE THREAD

**Issue by CN-hurui** [XKaguya/AutoReconnect-Remastered#8]
① After using this plugin, my server will encounter a problem where all players are unable to move, and restarting the turn will not work. I must execute softrestart
② Can players be allowed to use the. rp command to replace departing players instead of randomly selecting observers

**Comment by XKaguya** [comment]
> ① After using this plugin, my server will encounter a problem where all players are unable to move, and restarting the turn will not work. I must execute softrestart ② Can players be allowed to use the. rp command to replace departing players instead of randomly selecting observers

Version ? 1.15 and not the Exiled 9 one ?

**Comment by XKaguya** [comment]
> ① After using this plugin, my server will encounter a problem where all players are unable to move, and restarting the turn will not work. I must execute softrestart ② Can players be allowed to use the. rp command to replace departing players instead of randomly selecting observers

And sure. I'll make such feature in the near future.

**Comment by XKaguya** [comment]
I'm now close this issue due to no reply. And the new feature you've asked has been released.
