### ISSUE TITLE
command question

### ISSUE THREAD

**Issue by CN-hurui** [XKaguya/AutoReconnect-Remastered#9]
![image](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/a0a4de80-bd6b-48d8-89a8-01a9c0ccc1e9)
emm...the  rp command is same of deny.
 Can the rp broadcast can be configable?

**Comment by XKaguya** [comment]
> ![image](https://private-user-images.githubusercontent.com/57028271/338795522-a0a4de80-bd6b-48d8-89a8-01a9c0ccc1e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjE3NzYsIm5iZiI6MTcxODE2MTQ3NiwicGF0aCI6Ii81NzAyODI3MS8zMzg3OTU1MjItYTBhNGRlODAtYmQ2Yi00OGQ4LTg5YTgtMDFhOWMwY2NjMWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzMDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ODkxOTYzZjkxYzFkYzk2YjBiMmNlYmU5OWRhZGFmNzkyYjkxNzUzOTY0ODc2ZGM0ZWU5MGQ4MTZmYzQwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DwHa3xVq_KEyDau35Rg2bBH9Qr4v0nr-rbPMIqWm4Dw) emm...the rp command is same of deny. Can the rp broadcast can be configable?

额，复制的时候忘记改了。。。
广播是可以自定义的，我马上改

**Comment by XKaguya** [comment]
> ![image](https://private-user-images.githubusercontent.com/57028271/338795522-a0a4de80-bd6b-48d8-89a8-01a9c0ccc1e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjE5NTUsIm5iZiI6MTcxODE2MTY1NSwicGF0aCI6Ii81NzAyODI3MS8zMzg3OTU1MjItYTBhNGRlODAtYmQ2Yi00OGQ4LTg5YTgtMDFhOWMwY2NjMWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzMDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzBlOGNiZGNmYjI2MmJmMjg4MzJkZTZkMDhkYzE0NWU5Y2RkMGRmYzEyZmZkMDU1MjJiNThkNzU2ZmQ5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m-KJHNF1Nd2A6b1luIlyTssx_wEHv5LJmAyVYhMHVGQ) emm...the rp command is same of deny. Can the rp broadcast can be configable?

这个不是已经存在的功能吗
```
var message = string.Format(AutoReconnect.Instance.Config.DisconnectedMessage, pd.Class, player.Nickname);
```

**Comment by XKaguya** [comment]
Issue resolved.
rp feature have the following alias:

```
rp
replace
replaceplayer
```

**Comment by CN-hurui** [comment]
您好，我想试着在本地进行编译，但是程序集无法引用，请问您有程序集的相关文件吗
Hello, I want to try to compile locally, but the assembly cannot be referenced, do you have the related files of the assembly



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 12, 2024 12:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9)




 
Closed #9 as completed.

**Comment by XKaguya** [comment]
> 您好，我想试着在本地进行编译，但是程序集无法引用，请问您有程序集的相关文件吗 Hello, I want to try to compile locally, but the assembly cannot be referenced, do you have the related files of the assembly
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Jun 12, 2024 12:08 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9) Closed #9 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

去 [Exiled](https://github.com/Exiled-Team/EXILED) 下载最新版 解压那个 .tar.gz 里面就是

**Comment by CN-hurui** [comment]
我已经使用nuget获取了ex的包，但是有些引用如mirror.dll，0harmony.dll这类是无法直接添加程序集的😭😭，您可以指导一下吗



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 12, 2024 13:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9)




  
您好，我想试着在本地进行编译，但是程序集无法引用，请问您有程序集的相关文件吗 Hello, I want to try to compile locally, but the assembly cannot be referenced, do you have the related files of the assembly
 …
 ---Original--- From: @.&gt; Date: Wed, Jun 12, 2024 12:08 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9) Closed #9 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
去 Exiled 下载最新版 解压那个 .tar.gz 里面就是

**Comment by XKaguya** [comment]
> 我已经使用nuget获取了ex的包，但是有些引用如mirror.dll，0harmony.dll这类是无法直接添加程序集的😭😭，您可以指导一下吗
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Jun 12, 2024 13:03 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9) 您好，我想试着在本地进行编译，但是程序集无法引用，请问您有程序集的相关文件吗 Hello, I want to try to compile locally, but the assembly cannot be referenced, do you have the related files of the assembly … ---Original--- From: @.&gt; Date: Wed, Jun 12, 2024 12:08 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [XKaguya/AutoReconnect-Remastered] command question (Issue #9) Closed #9 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 去 Exiled 下载最新版 解压那个 .tar.gz 里面就是 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

里面有带 Harmony 的，你把这些解压丢一起，然后实在懒就去 SL服务器 根目录的 Managed 里面把所有 DLL 拖出来
你可能还需要用到 APublicizer 来使得 Assemble-CSharp.dll 里面的方法全部公开化，这样才能调用

然后再去VS/Rider里面引用整个文件夹里面的所有DLL就行。

**Comment by CN-hurui** [comment]
![image](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/8356813b-e84a-4e4b-89c8-c126c42a534c)
尝试引用的时候（添加程序集）总是报错，无法引用

**Comment by XKaguya** [comment]
> ![image](https://private-user-images.githubusercontent.com/57028271/338839674-8356813b-e84a-4e4b-89c8-c126c42a534c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzIxMjIsIm5iZiI6MTcxODE3MTgyMiwicGF0aCI6Ii81NzAyODI3MS8zMzg4Mzk2NzQtODM1NjgxM2ItZTg0YS00ZTRiLTg5YzgtYzEyNmM0MmE1MzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA1NTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjlhMDVkNDQ5ZDAwYWY3YzZlZDkxZjQ2ZGIzYjI3ZTNmODcwM2MxYTQ4MzU2YzMxYmM3OWY2NzFmODM3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xmjt7Z0Ms3_dGOdAqx87cP37bG4BfHS9xsjR5wP5KeM) 尝试引用的时候（添加程序集）总是报错，无法引用

额，我不知道你具体怎么操作的，这个报错你还是百度看看吧

**Comment by CN-hurui** [comment]
![image](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/207911e7-e150-4fa2-9276-9f0c1131fbb3)
var message = string.Format(AutoReconnect.Instance.Config.DisconnectedMessage, pd.Class, player.Nickname);
您这个这个好像是在观察者替代SCP之后会向全体玩家发送的消息，功能设计应该是可以在SCP玩家断开后向观察者角色发送.rp可以代替玩家的公告

**Comment by CN-hurui** [comment]
我是一名自学的编程新手，以下是我添加程序集的步骤：
![94SGNG}4RB8)OR@)M3LV9G7](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/e2dda269-eb44-491b-8ced-8a00ff64a394)
![14TEZZHMN`K0H5@UF( EEMW](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/f3d1642b-0a40-4f2b-a88d-0c45bf85a529)
![BY{68LV3GGL$_Z9UEX694@S](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/cc507238-9976-40af-9542-236a7ad4b7d3)
![L`C%@4XSD)X66Q%B6N IFUP](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/9b133d12-0e4d-46f3-b371-fb4061953b33)
![96%1~6Q115VT$H `}Z765XC](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/1c22bc85-a39e-41e0-a3d4-a8f7664d18a2)

**Comment by CN-hurui** [comment]
我是一名自学的编程新手，以下是我引用程序集的步骤：
![Collage_20240612_140847](https://github.com/XKaguya/AutoReconnect-Remastered/assets/57028271/6ec20df6-4a5d-4c0a-86d2-fbafeeed4faa)

**Comment by XKaguya** [comment]
> ![image](https://private-user-images.githubusercontent.com/57028271/338840089-207911e7-e150-4fa2-9276-9f0c1131fbb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzIzNDAsIm5iZiI6MTcxODE3MjA0MCwicGF0aCI6Ii81NzAyODI3MS8zMzg4NDAwODktMjA3OTExZTctZTE1MC00ZmEyLTkyNzYtOWYwYzExMzFmYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYWU4NmZkMWJkMGY5MDUyYmU2NTA1NDg3MjMxYjVhYWMxNjNkZjE5N2IyMGUwNzQyOTEzMDI0OTNkY2E5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1mDHtrlMO7i25WvHahhd0rTvSgWlU_a7s2nyJGvNytA) var message = string.Format(AutoReconnect.Instance.Config.DisconnectedMessage, pd.Class, player.Nickname); 您这个这个好像是在观察者替代SCP之后会向全体玩家发送的消息，功能设计应该是可以在SCP玩家断开后向观察者角色发送.rp可以代替玩家的公告

我复用了这段文本， 然后你的依赖为什么这样不行我也不清楚，我后期主要转Rider了
或许你可以点开程序集再下一层看看引用
